import type { ActivityItem, Asset, FamilyId, PipelineItem, PlatformFamily } from './types'

export const demoUsers = [
  { email: 'abhilash.vantaram@infovision.com', name: 'Abhilash', password: 'Aimplify@2026' },
  { email: 'balram.aggarwal@infovision.com', name: 'Balram', password: 'Aimplify@2026' },
  { email: 'dhanuvanth.senthilkumar@infovision.com', name: 'Dhanuvanth', password: 'Aimplify@2026' },
  { email: 'pratyoosh.patel@infovision.com', name: 'Pratyoosh', password: 'Aimplify@2026' },
  { email: 'renju.devi@infovision.com', name: 'Renju', password: 'Aimplify@2026' },
  { email: 'swetha.polumahanthi@infovision.com', name: 'Swetha', password: 'Aimplify@2026' },
]

export const families: PlatformFamily[] = [
  {
    id: 'atlas',
    name: 'Atlas',
    tagline: 'Data & Context Platform',
    color: '#16a8b7',
    description:
      'The data foundation that gives every platform family credibility: AI readiness, semantic context, master data management, and migration patterns.',
    whenToSell: [
      'Enterprise needs to make scattered data AI-ready',
      'Customer wants RAG but data spans many systems',
      'Data quality issues block an AI pilot expansion',
    ],
    dependsOn: ['Sentinel data governance guardrails', 'Nexus reference architecture'],
    enables: ['Reliable agents with governed context', 'Forge pipelines with trusted test data'],
    solutions: [
      { name: 'Foundation Sprint', description: '4-week data readiness assessment and remediation' },
      { name: 'AI Ready Data Estate', description: 'Semantic layer, embeddings, and retrieval infrastructure' },
      { name: 'Migration Factory', description: 'Automated data pipeline modernization' },
      { name: 'Master Data & Domain Context', description: 'Identify resolution and shared vocabulary' },
    ],
  },
  {
    id: 'forge',
    name: 'Forge',
    tagline: 'AI-Native Engineering Platform',
    color: '#d49b1f',
    description:
      'Reusable engineering accelerators for AI-assisted SDLC, quality automation, code migration, and evaluation workflows.',
    whenToSell: ['Delivery team needs SDLC acceleration', 'Legacy modernization needs repeatable patterns'],
    dependsOn: ['Nexus CI/CD templates', 'Sentinel compliance checks'],
    enables: ['Higher delivery throughput', 'Standardized engineering practices'],
    solutions: [
      { name: 'Vibe Coding Templates', description: 'Prompt and workflow patterns for assisted delivery' },
      { name: 'AI Testing & Eval Framework', description: 'LLM scoring, regression detection, and CI gates' },
      { name: 'Role Prompt Libraries', description: 'Reusable role-based prompts for delivery teams' },
    ],
  },
  {
    id: 'relay',
    name: 'Relay',
    tagline: 'Workflow & Agent Platform',
    color: '#7c4dff',
    description:
      'Composable agents and workflow automation assets for support, operations, document processing, and business process acceleration.',
    whenToSell: ['Manual processes need automation', 'Support tickets need triage and resolution assistance'],
    dependsOn: ['Atlas context', 'Sentinel runtime guardrails'],
    enables: ['Human-in-loop workflows', 'Reusable agent orchestration'],
    solutions: [
      { name: 'Agent Orchestration', description: 'Patterns for multi-agent workflows' },
      { name: 'Document Intelligence', description: 'Extraction, classification, and routing workflows' },
    ],
  },
  {
    id: 'sentinel',
    name: 'Sentinel',
    tagline: 'Governed Runtime & Managed AI Ops',
    color: '#c63c71',
    description:
      'Guardrails, observability, compliance, and runtime patterns for operating AI safely across delivery teams.',
    whenToSell: ['Customer needs secure AI rollout', 'Governance blocks production deployment'],
    dependsOn: ['Nexus shared infrastructure'],
    enables: ['Audit-ready AI operations', 'Risk-aware accelerator adoption'],
    solutions: [
      { name: 'Security & Compliance Guardrails', description: 'Audit, logging, and policy checks' },
      { name: 'Managed AI Ops', description: 'Runtime monitoring and incident workflows' },
    ],
  },
  {
    id: 'nexus',
    name: 'Nexus',
    tagline: 'Shared Platform Infrastructure',
    color: '#60646c',
    description:
      'Cross-cutting infrastructure, templates, deployment blueprints, and shared platform patterns for accelerators.',
    whenToSell: ['Multiple accelerators need a common deployment base'],
    dependsOn: ['Cloud landing zones', 'Enterprise platform standards'],
    enables: ['Reusable infrastructure', 'Lower setup time for new assets'],
    solutions: [
      { name: 'Reference Infrastructure', description: 'Cloud-native templates and baselines' },
      { name: 'CI/CD Starter Kits', description: 'Reusable deployment pipelines' },
    ],
  },
]

export const assets: Asset[] = [
  {
    id: 'atl-001',
    name: 'RAG Pipeline Patterns',
    familyId: 'atlas',
    category: 'AI Context',
    solution: 'AI Ready Data Estate',
    description: 'Production-grade ingestion, chunking, embedding, hybrid retrieval, and evaluation pipelines.',
    about:
      'A reusable blueprint for grounding enterprise AI applications with governed retrieval, source citations, and quality checks.',
    owner: 'Anika Desai',
    ownerInitials: 'AD',
    maturity: 'Demo-ready',
    effort: 'Medium',
    clouds: ['GCP', 'AWS', 'Azure'],
    tags: ['RAG', 'Embeddings', 'Vector Search'],
    demoUrl: 'https://example.com/demo/rag-pipeline',
    repoUrl: 'https://github.com/infovision/aimplify-rag-patterns',
    users: 14,
    deployments: 36,
    pipelines: 5,
    score: 88,
    architecture: ['Data Sources', 'Chunking Service', 'Vector Index', 'Retrieval API', 'Eval Harness'],
    quickStart: ['git clone https://github.com/infovision/aimplify-rag-patterns', 'npm install', 'npm run demo'],
    prerequisites: ['Cloud storage bucket', 'Embedding model access', 'Vector database'],
    dependencies: ['SEN-001 Security & Compliance Guardrails'],
    changelog: [
      { version: 'v0.5.0', date: 'Apr 12, 2026', note: 'Added hybrid retrieval evaluation' },
      { version: 'v0.4.1', date: 'Mar 22, 2026', note: 'Improved metadata filtering' },
    ],
  },
  {
    id: 'atl-002',
    name: 'Data Lifecycle Accelerator',
    familyId: 'atlas',
    category: 'DataOps',
    solution: 'Foundation Sprint',
    description: 'Data quality agent, pipeline monitoring, and metadata management on BigQuery and Dataflow.',
    about:
      'End-to-end DataOps with agentic AI: continuous monitoring of freshness, completeness, consistency, and lineage health.',
    owner: 'Anika Desai',
    ownerInitials: 'AD',
    maturity: 'Experimental',
    effort: 'High',
    clouds: ['GCP'],
    tags: ['DataOps', 'BigQuery', 'Data Quality'],
    demoUrl: 'https://example.com/demo/data-lifecycle',
    repoUrl: 'https://github.com/infovision/atlas-data-lifecycle',
    users: 4,
    deployments: 2,
    pipelines: 1,
    score: 88,
    architecture: ['Data Sources', 'Quality Agent', 'Pipeline Monitor', 'Metadata Catalog'],
    quickStart: [
      'git clone https://github.com/infovision/atlas-data-lifecycle',
      'terraform -chdir=infra init && terraform -chdir=infra apply',
    ],
    prerequisites: ['GCP with BigQuery', 'Terraform >= 1.5', 'Python 3.11', 'Dataplex API'],
    dependencies: ['SEN-002 Observability'],
    changelog: [
      { version: 'v0.3.4', date: 'Apr 1, 2026', note: 'Anomaly detection' },
      { version: 'v0.3.0', date: 'Mar 18, 2026', note: 'Pipeline failure diagnosis' },
    ],
  },
  {
    id: 'atl-003',
    name: 'Semantic Context & Mastering Kit',
    familyId: 'atlas',
    category: 'Master Data',
    solution: 'Master Data & Domain Context',
    description: 'Domain schema templates, identity resolution, and semantic layer bootstrapping for AI readiness.',
    about: 'Helps teams create shared business vocabulary and consistent context before applying agents.',
    owner: 'Maya Rao',
    ownerInitials: 'MR',
    maturity: 'Experimental',
    effort: 'High',
    clouds: ['AWS', 'GCP'],
    tags: ['Semantic Layer', 'MDM', 'Ontology'],
    users: 8,
    deployments: 1,
    pipelines: 2,
    score: 81,
    architecture: ['Domain Model', 'Identity Resolver', 'Semantic Catalog', 'API'],
    quickStart: ['npm run seed:domain', 'npm run inspect'],
    prerequisites: ['Source schema exports', 'Domain SME review'],
    dependencies: ['ATL-001 RAG Pipeline Patterns'],
    changelog: [{ version: 'v0.2.1', date: 'Apr 5, 2026', note: 'Added retail domain template' }],
  },
  {
    id: 'for-001',
    name: 'Vibe Coding Templates',
    familyId: 'forge',
    category: 'AI SDLC',
    solution: 'Vibe Coding Templates',
    description: 'Reusable delivery prompts, project scaffolds, review checklists, and implementation workflows.',
    about: 'A team starter kit for consistent AI-assisted delivery across discovery, build, test, and review.',
    owner: 'Priya Sharma',
    ownerInitials: 'PS',
    maturity: 'Battle-tested',
    effort: 'Low',
    clouds: ['Cloud agnostic'],
    tags: ['SDLC', 'Prompts', 'Delivery'],
    users: 44,
    deployments: 67,
    pipelines: 9,
    score: 96,
    architecture: ['Prompt Library', 'Task Templates', 'Review Checklist', 'Delivery Playbook'],
    quickStart: ['Clone template pack', 'Pick role prompt', 'Run checklist before PR'],
    prerequisites: ['GitHub Copilot or equivalent AI coding access'],
    dependencies: ['FOR-002 Role Prompt Libraries'],
    changelog: [{ version: 'v1.2.0', date: 'Apr 20, 2026', note: 'Added migration sprint workflow' }],
  },
  {
    id: 'for-002',
    name: 'Role Prompt Libraries',
    familyId: 'forge',
    category: 'Prompt Engineering',
    solution: 'Role Prompt Libraries',
    description: 'Curated role prompts for architects, QA, developers, data engineers, and support analysts.',
    about: 'Gives teams repeatable prompt behavior by role and project context.',
    owner: 'Lisa Chen',
    ownerInitials: 'LC',
    maturity: 'Battle-tested',
    effort: 'Low',
    clouds: ['Cloud agnostic'],
    tags: ['Prompts', 'Roles', 'Copilot'],
    users: 37,
    deployments: 42,
    pipelines: 4,
    score: 93,
    architecture: ['Role Catalog', 'Prompt Variants', 'Example Tasks'],
    quickStart: ['Select a role', 'Copy the prompt', 'Attach project context'],
    prerequisites: ['LLM access'],
    dependencies: [],
    changelog: [{ version: 'v1.1.0', date: 'Apr 18, 2026', note: 'Added product owner prompts' }],
  },
  {
    id: 'for-003',
    name: 'AI Testing & Eval Framework',
    familyId: 'forge',
    category: 'Quality Engineering',
    solution: 'AI Testing & Eval Framework',
    description: 'Prompt testing, LLM scoring, regression detection, and CI/CD integration for AI features.',
    about: 'Handles probabilistic LLM outputs through regression runners, LLM-as-judge, and behavioral tests.',
    owner: 'Deepa Krishnan',
    ownerInitials: 'DK',
    maturity: 'Validated',
    effort: 'Low',
    clouds: ['AWS', 'GCP', 'Azure'],
    tags: ['Testing', 'Evaluation', 'CI/CD'],
    users: 22,
    deployments: 22,
    pipelines: 8,
    score: 91,
    architecture: ['Test Runner', 'Eval Metrics', 'Regression Detector', 'CI/CD Plugin'],
    quickStart: ['pip install aimplify-ai-testing', 'aimplify-test init --project my-agent', 'aimplify-test run --suite behavioral'],
    prerequisites: ['LLM endpoint', 'Baseline dataset'],
    dependencies: ['FOR-002 Role Prompt Libraries'],
    changelog: [{ version: 'v0.8.4', date: 'Apr 7, 2026', note: 'GitHub Actions integration' }],
  },
  {
    id: 'rel-001',
    name: 'Slack Workflow Automator',
    familyId: 'relay',
    category: 'Process Automation',
    solution: 'Agent Orchestration',
    description: 'AI agent automating Slack workflows, approvals, reminders, and handoffs.',
    about: 'Turns conversational team workflows into traceable automations with escalation and audit trails.',
    owner: 'Arjun Mehta',
    ownerInitials: 'AM',
    maturity: 'Demo-ready',
    effort: 'Medium',
    clouds: ['Azure', 'AWS'],
    tags: ['Slack', 'Workflow', 'Agent'],
    users: 12,
    deployments: 7,
    pipelines: 3,
    score: 72,
    architecture: ['Slack App', 'Intent Classifier', 'Workflow Agent', 'Approval Queue'],
    quickStart: ['Create Slack app', 'Set webhook URL', 'npm run worker'],
    prerequisites: ['Slack app credentials', 'Queue service'],
    dependencies: ['SEN-001 Security & Compliance Guardrails'],
    changelog: [{ version: 'v0.4.0', date: 'Apr 10, 2026', note: 'Added approval reminders' }],
  },
  {
    id: 'rel-002',
    name: 'PDF Contract Analyzer',
    familyId: 'relay',
    category: 'Document Intelligence',
    solution: 'Document Intelligence',
    description: 'Extracts clauses, risks, obligations, and summary views from contract PDFs.',
    about: 'A document agent pipeline for contract intake and review acceleration.',
    owner: 'Lisa Chen',
    ownerInitials: 'LC',
    maturity: 'Demo-ready',
    effort: 'Medium',
    clouds: ['Azure'],
    tags: ['PDF', 'Contracts', 'Extraction'],
    users: 18,
    deployments: 12,
    pipelines: 6,
    score: 91,
    architecture: ['PDF Parser', 'Clause Extractor', 'Risk Scorer', 'Review UI'],
    quickStart: ['Upload PDF', 'Run analyzer', 'Export summary'],
    prerequisites: ['Document AI endpoint', 'Storage bucket'],
    dependencies: ['ATL-001 RAG Pipeline Patterns'],
    changelog: [{ version: 'v0.6.1', date: 'Apr 14, 2026', note: 'Added obligation extraction' }],
  },
  {
    id: 'sen-001',
    name: 'Security & Compliance Guardrails',
    familyId: 'sentinel',
    category: 'Governance',
    solution: 'Security & Compliance Guardrails',
    description: 'Policy checks, audit logging, sanitization, and compliance gates for AI assets.',
    about: 'The baseline guardrail package for safely moving assets from demo to customer delivery.',
    owner: 'Suresh P.',
    ownerInitials: 'SP',
    maturity: 'Validated',
    effort: 'Medium',
    clouds: ['AWS', 'Azure', 'GCP'],
    tags: ['Security', 'Compliance', 'Audit'],
    users: 20,
    deployments: 28,
    pipelines: 5,
    score: 94,
    architecture: ['Policy Engine', 'Sanitizer', 'Audit Log', 'Compliance Report'],
    quickStart: ['Configure policies', 'Attach middleware', 'Review audit report'],
    prerequisites: ['Policy catalog', 'Logging sink'],
    dependencies: [],
    changelog: [{ version: 'v0.9.0', date: 'Apr 21, 2026', note: 'Added PII policy pack' }],
  },
  {
    id: 'nex-001',
    name: 'GitHub Actions Integration',
    familyId: 'nexus',
    category: 'Infrastructure',
    solution: 'CI/CD Starter Kits',
    description: 'Reusable CI/CD workflows for scans, test runs, and cloud deployments.',
    about: 'A shared pipeline foundation so accelerator teams do not rebuild delivery infrastructure repeatedly.',
    owner: 'Deepak J.',
    ownerInitials: 'DJ',
    maturity: 'Demo-ready',
    effort: 'Low',
    clouds: ['AWS', 'Azure', 'GCP'],
    tags: ['GitHub', 'CI/CD', 'Terraform'],
    users: 16,
    deployments: 29,
    pipelines: 4,
    score: 86,
    architecture: ['Workflow Templates', 'Secrets Model', 'Environment Gates', 'Deployment Jobs'],
    quickStart: ['Copy workflow', 'Set environment secrets', 'Run deployment'],
    prerequisites: ['GitHub repo', 'Cloud credentials'],
    dependencies: ['SEN-001 Security & Compliance Guardrails'],
    changelog: [{ version: 'v0.7.2', date: 'Apr 16, 2026', note: 'Added Azure deployment template' }],
  },
]

export const pipelineItems: PipelineItem[] = [
  {
    id: 'sub-001',
    assetName: 'Slack Workflow Automator',
    familyId: 'relay',
    category: 'Process Automation',
    solution: 'Agent Orchestration',
    author: 'Arjun Mehta',
    authorInitials: 'AM',
    status: 'AI Review',
    score: 72,
    description: 'Agent automating Slack workflows.',
    ownerEmail: 'arjun.mehta@infovision.com',
    repoUrl: 'https://github.com/infovision/slack-workflow-automator',
    demoUrl: 'https://example.com/demo/slack-workflow',
    clouds: ['AWS', 'Azure'],
    maturity: 'Demo-ready',
    attachments: [
      { label: 'Workflow demo', url: 'https://example.com/demo/slack-workflow', type: 'Video' },
      { label: 'Prompt pack', url: 'https://example.com/prompts/slack-workflow', type: 'Prompt' },
    ],
    submittedAt: '2026-05-07',
  },
  {
    id: 'sub-002',
    assetName: 'PDF Contract Analyzer',
    familyId: 'relay',
    category: 'Document Intelligence',
    solution: 'Document Intelligence',
    author: 'Lisa Chen',
    authorInitials: 'LC',
    status: 'Manual Approval',
    score: 91,
    description: 'Clause extraction and risk scoring for contracts.',
    ownerEmail: 'lisa.chen@infovision.com',
    repoUrl: 'https://github.com/infovision/pdf-contract-analyzer',
    demoUrl: 'https://example.com/demo/pdf-contract',
    clouds: ['Azure'],
    maturity: 'Demo-ready',
    attachments: [
      { label: 'Contract walkthrough', url: 'https://example.com/demo/pdf-contract', type: 'Video' },
      { label: 'Sample clauses', url: 'https://example.com/docs/sample-clauses', type: 'Document' },
    ],
    submittedAt: '2026-05-06',
  },
  {
    id: 'sub-003',
    assetName: 'Terraform Cost Estimator',
    familyId: 'sentinel',
    category: 'Governance',
    solution: 'Managed AI Ops',
    author: 'Priya Sharma',
    authorInitials: 'PS',
    status: 'Approved',
    score: 95,
    description: 'Cost estimation before Terraform apply.',
    ownerEmail: 'priya.sharma@infovision.com',
    repoUrl: 'https://github.com/infovision/terraform-cost-estimator',
    demoUrl: 'https://example.com/demo/terraform-cost',
    clouds: ['AWS', 'GCP'],
    maturity: 'Validated',
    attachments: [
      { label: 'Estimator demo', url: 'https://example.com/demo/terraform-cost', type: 'Video' },
    ],
    submittedAt: '2026-05-05',
    approvedAt: '2026-05-06',
  },
]

export const activities: ActivityItem[] = [
  { id: 'act-001', person: 'Suresh P.', action: 'promoted IT Ops Agent to', target: 'Validated', familyId: 'sentinel', time: '1h ago' },
  { id: 'act-002', person: 'Lisa Chen', action: 'submitted', target: 'PDF Contract Analyzer', familyId: 'relay', time: '4h ago' },
  { id: 'act-003', person: 'Priya S.', action: 'published', target: 'Terraform Cost Estimator', familyId: 'sentinel', time: '1d ago' },
  { id: 'act-004', person: 'Tanya I.', action: 'added hierarchical pattern to', target: 'Multi-Agent Orchestration', familyId: 'relay', time: '2d ago' },
  { id: 'act-005', person: 'Deepak J.', action: 'shipped GitHub Actions integration for', target: 'AI Testing Framework', familyId: 'forge', time: '3d ago' },
]

export function getFamily(id: FamilyId) {
  return families.find((family) => family.id === id) ?? families[0]
}

export function familyAssets(id: FamilyId) {
  return assets.filter((asset) => asset.familyId === id)
}

export function familyCount(id: FamilyId) {
  return familyAssets(id).length
}
